"""Alert and notification management for the LineGuard safety system."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Callable, Dict, List, Optional


class AlertType(Enum):
    """Classification of safety alerts."""

    ZONE_VIOLATION = "zone_violation"
    SENSOR_THRESHOLD = "sensor_threshold"
    EQUIPMENT_FAULT = "equipment_fault"
    EMERGENCY = "emergency"
    SENSOR_OFFLINE = "sensor_offline"
    FIRE = "fire"
    GAS_LEAK = "gas_leak"


class AlertStatus(Enum):
    """Lifecycle status of an alert."""

    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"
    ESCALATED = "escalated"


class AlertPriority(Enum):
    """Priority levels that determine escalation and response urgency."""

    INFO = 1
    WARNING = 2
    HIGH = 3
    CRITICAL = 4


# Mapping from alert type to default priority
_DEFAULT_PRIORITY: Dict[AlertType, AlertPriority] = {
    AlertType.ZONE_VIOLATION: AlertPriority.WARNING,
    AlertType.SENSOR_THRESHOLD: AlertPriority.HIGH,
    AlertType.EQUIPMENT_FAULT: AlertPriority.HIGH,
    AlertType.EMERGENCY: AlertPriority.CRITICAL,
    AlertType.SENSOR_OFFLINE: AlertPriority.WARNING,
    AlertType.FIRE: AlertPriority.CRITICAL,
    AlertType.GAS_LEAK: AlertPriority.CRITICAL,
}


@dataclass
class Alert:
    """A single safety alert generated by the monitoring system."""

    alert_id: str
    alert_type: AlertType
    message: str
    timestamp: str
    source_id: str
    priority: AlertPriority = AlertPriority.WARNING
    status: AlertStatus = AlertStatus.ACTIVE
    acknowledged_by: Optional[str] = None
    resolution_notes: str = ""

    def acknowledge(self, operator_id: str) -> None:
        """Mark this alert as acknowledged by *operator_id*."""
        if self.status == AlertStatus.ACTIVE:
            self.status = AlertStatus.ACKNOWLEDGED
            self.acknowledged_by = operator_id

    def resolve(self, notes: str = "") -> None:
        """Mark this alert as resolved."""
        self.status = AlertStatus.RESOLVED
        self.resolution_notes = notes

    def escalate(self) -> None:
        """Escalate this alert to higher-priority handling."""
        self.status = AlertStatus.ESCALATED
        if self.priority != AlertPriority.CRITICAL:
            self.priority = AlertPriority(self.priority.value + 1)

    @property
    def is_active(self) -> bool:
        """Return True when the alert is still open (active or escalated)."""
        return self.status in (AlertStatus.ACTIVE, AlertStatus.ESCALATED)


# Type alias for notification callbacks
NotificationHandler = Callable[[Alert], None]


class AlertManager:
    """Manage alerts generated by the safety monitoring system."""

    def __init__(self) -> None:
        self._alerts: List[Alert] = []
        self._alert_counter: int = 0
        self._handlers: List[NotificationHandler] = []

    # ------------------------------------------------------------------ #
    # Handler registration                                                #
    # ------------------------------------------------------------------ #

    def register_handler(self, handler: NotificationHandler) -> None:
        """Register a callback that is invoked whenever a new alert is raised."""
        self._handlers.append(handler)

    def unregister_handler(self, handler: NotificationHandler) -> bool:
        """Remove a previously registered handler.  Returns True if found."""
        try:
            self._handlers.remove(handler)
            return True
        except ValueError:
            return False

    # ------------------------------------------------------------------ #
    # Alert lifecycle                                                     #
    # ------------------------------------------------------------------ #

    def raise_alert(
        self,
        alert_type: AlertType,
        message: str,
        timestamp: str,
        source_id: str,
        priority: Optional[AlertPriority] = None,
    ) -> Alert:
        """Create and register a new alert, then notify all handlers."""
        self._alert_counter += 1
        effective_priority = priority or _DEFAULT_PRIORITY.get(
            alert_type, AlertPriority.WARNING
        )
        alert = Alert(
            alert_id=f"A{self._alert_counter:06d}",
            alert_type=alert_type,
            message=message,
            timestamp=timestamp,
            source_id=source_id,
            priority=effective_priority,
        )
        self._alerts.append(alert)
        self._notify(alert)
        return alert

    def acknowledge_alert(self, alert_id: str, operator_id: str) -> bool:
        """Acknowledge an alert by ID.  Returns True if found and updated."""
        alert = self._find(alert_id)
        if alert is None:
            return False
        alert.acknowledge(operator_id)
        return True

    def resolve_alert(self, alert_id: str, notes: str = "") -> bool:
        """Resolve an alert by ID.  Returns True if found and updated."""
        alert = self._find(alert_id)
        if alert is None:
            return False
        alert.resolve(notes)
        return True

    def escalate_alert(self, alert_id: str) -> bool:
        """Escalate an alert by ID.  Returns True if found and updated."""
        alert = self._find(alert_id)
        if alert is None:
            return False
        alert.escalate()
        return True

    # ------------------------------------------------------------------ #
    # Queries                                                             #
    # ------------------------------------------------------------------ #

    @property
    def active_alerts(self) -> List[Alert]:
        """Return all currently active or escalated alerts."""
        return [a for a in self._alerts if a.is_active]

    @property
    def critical_alerts(self) -> List[Alert]:
        """Return active alerts with CRITICAL priority."""
        return [
            a for a in self.active_alerts if a.priority == AlertPriority.CRITICAL
        ]

    @property
    def all_alerts(self) -> List[Alert]:
        """Return all alerts regardless of status."""
        return list(self._alerts)

    def get_alert(self, alert_id: str) -> Optional[Alert]:
        """Return the alert with *alert_id*, or None if not found."""
        return self._find(alert_id)

    # ------------------------------------------------------------------ #
    # Internal helpers                                                    #
    # ------------------------------------------------------------------ #

    def _find(self, alert_id: str) -> Optional[Alert]:
        for alert in self._alerts:
            if alert.alert_id == alert_id:
                return alert
        return None

    def _notify(self, alert: Alert) -> None:
        for handler in self._handlers:
            handler(alert)
